-- Crear tablas de base
CREATE TABLE CUERPO_ESPACIAL (
    Id NUMBER PRIMARY KEY,
    Cod VARCHAR(10) UNIQUE,
    Nombre VARCHAR2(100),
    Masa NUMBER,
    Composicion VARCHAR2(100),
    Radio NUMBER,
    Id_Orbita NUMBER, 
    FOREIGN KEY (Id_Orbita) REFERENCES CUERPO_ESPACIAL(Id)
);

CREATE TABLE ASTEROIDE (
    Id NUMBER PRIMARY KEY,
    Tipo_Espectral VARCHAR2(50),
    Peligrosidad NUMBER,
    FOREIGN KEY (Id) REFERENCES CUERPO_ESPACIAL(Id)
);

CREATE TABLE ESTRELLA (
    Id NUMBER PRIMARY KEY,
    Temperatura NUMBER,
    Luminosidad NUMBER,
    FOREIGN KEY (Id) REFERENCES CUERPO_ESPACIAL(Id)
);

CREATE TABLE AGUJERO_NEGRO (
    Id NUMBER PRIMARY KEY,
    Acrecion NUMBER,
    FOREIGN KEY (Id) REFERENCES CUERPO_ESPACIAL(Id)
);

CREATE TABLE PLANETA (
    Id NUMBER PRIMARY KEY,
    Atmosfera VARCHAR2(100),
    FOREIGN KEY (Id) REFERENCES CUERPO_ESPACIAL(Id)
);

CREATE TABLE PUERTO_ESPACIAL (
    Cod_Cuerpo VARCHAR2(10),
    Id_Puerto NUMBER,
    Capacidad NUMBER,
    Anio_Inauguracion NUMBER,
    Distancia NUMBER, -- Distancia al cuerpo espacial
    Ultima_Modificacion DATE DEFAULT SYSDATE,
    PRIMARY KEY (Cod_Cuerpo, Id_Puerto),
    FOREIGN KEY (Cod_Cuerpo) REFERENCES CUERPO_ESPACIAL(Cod)
);

CREATE TABLE NAVE_TRIPULADA (
    Id_Nave NUMBER PRIMARY KEY
);

CREATE TABLE VIAJE_ESPACIAL (
    Id NUMBER PRIMARY KEY,
    Fecha_Salida DATE,
    Fecha_Llegada DATE,
    Id_Cuerpo_Salida VARCHAR2(10),
    Id_Puerto_Salida NUMBER,
    Id_Cuerpo_Llegada VARCHAR2(10),
    Id_Puerto_Llegada NUMBER,
    FOREIGN KEY (Id_Cuerpo_Salida, Id_Puerto_Salida) REFERENCES PUERTO_ESPACIAL(Cod_Cuerpo, Id_Puerto),
    FOREIGN KEY (Id_Cuerpo_Llegada, Id_Puerto_Llegada) REFERENCES PUERTO_ESPACIAL(Cod_Cuerpo, Id_Puerto)
);

-- Tablas relacionadas con las tripulaciones
CREATE TABLE TRIPULANTE (
    DNI CHAR(8) PRIMARY KEY,
    Nombre VARCHAR2(100),
    Apellido VARCHAR2(100)
);

CREATE TABLE TRABAJADOR (
    DNI CHAR(8) PRIMARY KEY,
    Salario NUMBER,
    Experiencia NUMBER,
    FOREIGN KEY (DNI) REFERENCES TRIPULANTE(DNI)
);

CREATE TABLE VIAJERO (
    DNI CHAR(8) PRIMARY KEY,
    Categoria VARCHAR2(50),
    Equipaje NUMBER,
    FOREIGN KEY (DNI) REFERENCES TRIPULANTE(DNI)
);

CREATE TABLE ENCARGADO (
    DNI CHAR(8) PRIMARY KEY,
    Responsabilidad VARCHAR2(100),
    FOREIGN KEY (DNI) REFERENCES TRABAJADOR(DNI)
);

CREATE TABLE INGENIERO (
    DNI CHAR(8) PRIMARY KEY,
    Especializacion VARCHAR2(100),
    FOREIGN KEY (DNI) REFERENCES TRABAJADOR(DNI)
);

CREATE TABLE INGENIERO_ENCARGADO (
    DNI CHAR(8) PRIMARY KEY,
    Rango VARCHAR2(50),
    FOREIGN KEY (DNI) REFERENCES INGENIERO(DNI),
    FOREIGN KEY (DNI) REFERENCES ENCARGADO(DNI)
);

CREATE TABLE PILOTO (
    DNI CHAR(8) PRIMARY KEY,
    Licencia VARCHAR2(50),
    FOREIGN KEY (DNI) REFERENCES TRABAJADOR(DNI)
);

CREATE TABLE AZAFATO (
    DNI CHAR(8) PRIMARY KEY,
    Primeros_Auxilios CHAR(1),
    FOREIGN KEY (DNI) REFERENCES TRABAJADOR(DNI)
);

CREATE TABLE IDIOMAS (
    DNI CHAR(8),
    Idioma VARCHAR2(50),
    PRIMARY KEY (DNI, Idioma),
    FOREIGN KEY (DNI) REFERENCES AZAFATO(DNI)
);

-- Relación PARTICIPA
CREATE TABLE PARTICIPA (
    Id_Viaje NUMBER,
    Id_Nave NUMBER,
    DNI CHAR(8),
    PRIMARY KEY (Id_Viaje, Id_Nave, DNI),
    FOREIGN KEY (Id_Viaje) REFERENCES VIAJE_ESPACIAL(Id),
    FOREIGN KEY (Id_Nave) REFERENCES NAVE_TRIPULADA(Id_Nave),
    FOREIGN KEY (DNI) REFERENCES TRIPULANTE(DNI)
);

-- Tablas para especificidades de las naves
CREATE TABLE MERCANCIA (
    Id NUMBER PRIMARY KEY,
    Id_Nave NUMBER,
    Cantidad_Carga NUMBER,
    FOREIGN KEY (Id_Nave) REFERENCES NAVE_TRIPULADA(Id_Nave)
);

CREATE TABLE BELICO (
    Id NUMBER PRIMARY KEY,
    Id_Nave NUMBER,
    Cantidad_Armamento NUMBER,
    FOREIGN KEY (Id_Nave) REFERENCES NAVE_TRIPULADA(Id_Nave)
);

CREATE TABLE TRANSPORTE (
    Id NUMBER PRIMARY KEY,
    Id_Nave NUMBER,
    Maximo_Pasajeros NUMBER,
    FOREIGN KEY (Id_Nave) REFERENCES NAVE_TRIPULADA(Id_Nave)
);
