-- Eliminar tablas relacionadas primero
DROP TABLE IDIOMAS CASCADE CONSTRAINTS;
DROP TABLE AZAFATO CASCADE CONSTRAINTS;
DROP TABLE PILOTO CASCADE CONSTRAINTS;
DROP TABLE INGENIERO_ENCARGADO CASCADE CONSTRAINTS;
DROP TABLE INGENIERO CASCADE CONSTRAINTS;
DROP TABLE ENCARGADO CASCADE CONSTRAINTS;
DROP TABLE VIAJERO CASCADE CONSTRAINTS;
DROP TABLE TRABAJADOR CASCADE CONSTRAINTS;
DROP TABLE TRIPULANTE CASCADE CONSTRAINTS;
DROP TABLE PARTICIPA CASCADE CONSTRAINTS;
DROP TABLE TRANSPORTE CASCADE CONSTRAINTS;
DROP TABLE BELICO CASCADE CONSTRAINTS;
DROP TABLE MERCANCIA CASCADE CONSTRAINTS;

-- Eliminar tablas principales
DROP TABLE VIAJE_ESPACIAL CASCADE CONSTRAINTS;
DROP TABLE NAVE_TRIPULADA CASCADE CONSTRAINTS;
DROP TABLE PUERTO_ESPACIAL CASCADE CONSTRAINTS;
DROP TABLE PLANETA CASCADE CONSTRAINTS;
DROP TABLE AGUJERO_NEGRO CASCADE CONSTRAINTS;
DROP TABLE ESTRELLA CASCADE CONSTRAINTS;
DROP TABLE ASTEROIDE CASCADE CONSTRAINTS;
DROP TABLE CUERPO_ESPACIAL CASCADE CONSTRAINTS;
